title = "monadiq"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]

  # Google Analitycs
  googleAnalitycsID = "Your ID"
  description = "monadiq"
  author = "monadiq"
  
  
  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# Multilangual : FR / EN
[Languages]
  ######## english language
  [Languages.en]
  languageName = "En"
    weight = 2
    languageCode = "en-us"
    title = "Monadiq"
    dateFormat = "January 2, 2006"
    home = "Home"

    
  [Languages.en.menu]

    # [[Languages.en.menu.header]]
    #   weight = 2
    #   name = "Work"
    #   url = "/work"
    # [[Languages.en.menu.header]]
    #   weight = 3
    #   name = "Blog"
    #   url = "/blog"
    # [[Languages.en.menu.header]]
    #   weight = 4
    #   name = "Service"
    #   url = "/service"
    [[Languages.en.menu.header]]
      weight = 5
      name = "Contact"
      url = "#contact-form"

    [[Languages.en.menu.footer]]
      weight = 1
      name = "About us"
      url = "#about-us"
    [[Languages.en.menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#contact-"
    # [[Languages.en.menu.footer]]
    #   weight = 3
    #   name = "How it works"
    #   url = "#"
    # [[Languages.en.menu.footer]]
    #   weight = 4
    #   name = "Blog"
    #   url = "#"
    # [[Languages.en.menu.footer]]
    #   weight = 5
    #   name = "Terms"
    #   url = "#"

  [Languages.en.params.slider]
    enable = true
    title = "Cloud Application &amp; Devops Consulting"
    subtitle = "Let us do the work and quide your team.<br/> You and your team can focus on what's important to you."
    # bgImage = "img/slider-bg.webp"
    # bgImageAlt = "img/slider-bg.jpg"

  [Languages.en.params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About Us"
    italic = "\"In a functional mathematics a monad acts as a container that abstracts quirks in the computations, and lets you focus more on what you want to do with the contained values.\""
    paragraph = "We see ourselves as the monads of the cloud architecture world. Being \"monadiq\" we help you with your adoption of or improvement of your cloud architecutre. Experts in applications, devops, and cloud architecture we can bring you the developer exeperience you need."

  [Languages.en.params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [Languages.en.params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/feature-bg.webp"
    bgImageAlt = "img/feature-bg.jpg"
    content = "We can help get your big ideas big or small, startup or enterprise became a reality."
    # [Languages.en.params.feature.button]
    #   caption = "View Works"
    #   url = "#"

  # [Languages.en.params.call]
  #   enable = true
  #   bgImage = "img/call-to-action-bg.jpg"
  #   title = "We design delightful digital experiences."
  #   paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [Languages.en.params.contact]
    enable = false
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    # [Languages.en.params.contact.form]
    #   name = "Your name"
    #   email = "Your email"
    #   subject = "Your subject"
    #   message = "Your message"
    #   button = "Send message"
    [Languages.en.params.contact.box]
      title = "Email Us"
      address = "P.O Box"
      email = "Email: contact@monadiq.com"
      phone = "Phone: +88 01672 506 744"
    # [Languages.en.params.contact.gmaps]
    #   title = "We Also Count in Google Maps"
