# Page settings
baseurl = "/"
title = "monadiq"
languageCode = "en-us"
theme = "pmc-landing"

[params]
  
  # Meta
  author = "Monadiq LLC"
  email = "contact@monadiq.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Hero section
  [params.hero]
    title = "monadiq"
    subtitle = "launching soon!"